name: GitHub Actions Demo
run-name: Usha is testing out GitHub Actions 🚀
on: [push]

jobs:
  build:
    name: Basic Example
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.